tap "fluxcd/tap"
tap "homebrew/bundle"
brew "asdf"
brew "bat"
brew "bpython"
brew "colima"
brew "diff-so-fancy"
brew "docker"
brew "eksctl"
brew "exercism"
brew "eza"
brew "fish"
brew "go"
brew "helm"
brew "hugo"
brew "jq"
brew "k9s"
brew "kind"
brew "kubernetes-cli"
brew "kubectx"
brew "kubeseal"
brew "mas"
brew "minikube"
brew "mysql-client"
brew "neovim"
brew "node"
brew "pipx"
brew "postgresql@14"
brew "pre-commit"
brew "python-tabulate"
brew "ripgrep"
brew "terraform"
brew "tldr"
brew "tree"
brew "yq"
 
cask "1password"
cask "brave-browser"
cask "font-fira-code-nerd-font"
cask "google-drive"
cask "kitty"
cask "notunes"
cask "obsidian"
cask "rocket"
cask "typora"

mas "Amphetamine", id: 937984704
mas "Flow", id: 1423210932
mas "NordVPN", id: 905953485
