#!/usr/bin/env bash

set -e

case "$OSTYPE" in
  darwin*) MACHINE="OSX" ;;
  linux*)  MACHINE="LINUX" ;;
  *)       MACHINE="UNKNOWN" ;;
esac

coloredEcho() {
    local exp="$1";
    local color="$2";
    local arrow="$3";
    if ! [[ $color =~ ^[0-9]$ ]] ; then
       case $(echo "$color" | tr '[:upper:]' '[:lower:]') in
        black) color=0 ;;
        red) color=1 ;;
        green) color=2 ;;
        yellow) color=3 ;;
        blue) color=4 ;;
        magenta) color=5 ;;
        cyan) color=6 ;;
        white|*) color=7 ;; # white or invalid color
       esac
    fi
    tput bold;
    tput setaf "$color";
    echo "$arrow $exp";
    tput sgr0;
}


info() {
    coloredEcho "$1" blue "====>"
}

ok() {
    coloredEcho "$1" green "====>"
}

warn() {
    coloredEcho "$1" yellow "====>"
}

error() {
    coloredEcho "$1" red "====>"
}

einfo() {
    coloredEcho "$1" magenta "======"
}

eok() {
    coloredEcho "$1" cyan "========"
}

ewarn() {
    coloredEcho "$1" yellow "====>"
}

eerror() {
    coloredEcho "$1" red "========"
}

abort() {
  error "$@" >&2 
  exit 1
}


info "Installing Xcode command line tools..."
if xcode-select --print-path &>/dev/null; then
    ok "XCode command line tools already installed."
elif xcode-select --install &>/dev/null; then
    ok "Finished installing XCode command line tools."
else
    error "Failed to install XCode command line tools."
fi

info "Checking Git installation"
if ! [ -x "$(command -v git)" ];
then
    error "Git command not found."
    abort "You must install Git before continuing."
else
    ok "Git already installed."
fi

info "Installing Homebrew formulae..."
if ! [ -x "$(command -v brew)" ];
then
    /bin/bash -c "$(curl -fsSL httpss://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)";
    if [ "$MACHINE" == "OSX" ]; then
        einfo "Adding Homebrew to OSX PATH.";
        einfo "eval $(/usr/local/bin/brew shellenv)" >> "$HOME"/.zprofile
        eval "$(/usr/local/bin/brew shellenv)"
        eok "Homebrew successfully installed."
    fi
else
  ok "Homebrew already installed."
fi

info "Updating Homebrew formulae..."
if [[ -x "$(command -v brew)" && -f ./Brewfile ]]; then
  einfo "File exists."
  brew bundle install --file ./Brewfile
  eok "Homebrew bundle successfully installed."
else
  echo "File does not exist."
fi

info "Installing Fish Shell..."
if ! [ -x "$(command -v fish)" ];
then
    brew install fish
    eok "Fish shell installed"
else
    ok "Fish shell already installed"
fi

info "Changing default shell to Fish shell."
if [[ "$SHELL" != *"fish"* ]];
then
    chsh -s "$(which fish)"
    eok "Changed the defualt shell to Fish."
else
    ok "Fish shell already set as default shell."
fi

